name: megastream
channels:
   - conda-forge
   - pytorch 
   - anaconda
   - defaults
dependencies:
  - python=3.9
  - pip
  - wget
  - python-wget
  - pytorch==1.11.0
  - torchvision==0.12.0
  - torchaudio==0.11.0
  - cudatoolkit==11.3.1
  - pinocchio
  - pillow
  - rclone
  - pip:
      - torchmetrics==0.10.3
      - segmentation-models-pytorch==0.3.3
      - ultralytics
      - meshcat
      - omegaconf
      - simplejson
      - line_profiler 
      - opencv-python
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - panda3d
      - joblib
      - xarray 
      - pandas
      - matplotlib
      - bokeh
      - plyfile 
      - trimesh 
      - ipdb 
      - panda3d-gltf
      - colorama
      - pyyaml
      - scipy
      - pypng
      - h5py 
      - seaborn
      - kornia 
      - pyarrow 
      - dt_apriltags 
      - open3d
      - structlog
      - imageio
      - progressbar
      - pyyaml
      - psutil
      - webdataset
      - opencv-contrib-python 
      - roma 
      - torchgeometry
      - omegaconf
      - fvcore
      - iopath
      - pycocotools 
      - matplotlib 
      - onnxruntime 
      - onnx
      - ffmpeg
      - gdown
      - ruamel.yaml
      - pyrender
      - wandb
      - distinctipy
      - scikit-image
      - imgaug
      - omegaconf
      - ray
      - coremltools
      - flask
      - flask-socketio